apiVersion: v1
kind: ConfigMap
metadata:
  name: manage-${NAMESPACE_RAW}-configmap
  namespace: controller
data:
  DOMAIN: $DOMAIN
  BASE_URL: $BASE_URL

  ETCD_SERVICE_NAME: $ETCD_SERVICE_NAME
  REDIS_SERVICE_NAME: $REDIS_SERVICE_NAME
  KEYCLOAK_SERVICE_NAME: $KEYCLOAK_SERVICE_NAME
  MYSQL_SERVICE_NAME: $MYSQL_SERVICE_NAME
  POSTGRES_SERVICE_NAME: $POSTGRES_SERVICE_NAME
  PROMETHEUS_SERVICE_NAME: $PROMETHEUS_SERVICE_NAME
  IPDRAWER_SERVICE_NAME: $IPDRAWER_SERVICE_NAME
  DATABASE_NAMESPACE: $DATABASE_NAMESPACE
  SUPERVISOR_SERVICE_NAME: $SUPERVISOR_SERVICE_NAME
  IPDRAWER_PORT: "$IPDRAWER_PORT"
  PG_USERNAME: "$PG_USERNAME"
  PG_DB_NAME: "$PG_DB_NAME"

  CYLONIX_ADMIN_EMAIL: "$CYLONIX_ADMIN_EMAIL"
  CYLONIX_ADMIN_FIRST_NAME: "$CYLONIX_ADMIN_FIRST_NAME"
  CYLONIX_ADMIN_LAST_NAME: "$CYLONIX_ADMIN_LAST_NAME"

  GOOGLE_LOGIN_CLIENT_ID: "$GOOGLE_LOGIN_CLIENT_ID"

  APPLE_LOGIN_CLIENT_ID: "$APPLE_LOGIN_CLIENT_ID"
  APPLE_LOGIN_CLIENT_SECRET: /etc/secrets/apple/private-key.p8
  APPLE_LOGIN_TEAM_ID: "$APPLE_LOGIN_TEAM_ID"
  APPLE_LOGIN_KEY_ID: "$APPLE_LOGIN_KEY_ID"

  SEND_EMAIL_PROVIDER: "$SEND_EMAIL_PROVIDER"
  SEND_EMAIL_FROM_ADDRESS: "$SEND_EMAIL_FROM_ADDRESS"
  SEND_EMAIL_LOCAL_NAME: "$SEND_EMAIL_LOCAL_NAME"

  CYLONIX_MANAGER_NO_TLS: "$CYLONIX_MANAGER_NO_TLS"

  HEADSCALE_BASE_DOMAIN: "$HEADSCALE_BASE_DOMAIN"
