apiVersion: v1
kind: ConfigMap
metadata:
  name: supervisor-configmap
  namespace: controller
data:
  DOMAIN: $DOMAIN
  POSTGRES_SERVICE_NAME: $POSTGRES_SERVICE_NAME
  INFLUXDB_SERVICE_NAME: $INFLUXDB_SERVICE_NAME
  INFLUXDB_TOKEN: $INFLUXDB_TOKEN
  IPDRAWER_SERVICE_NAME: $IPDRAWER_SERVICE_NAME
  DATABASE_NAMESPACE: $DATABASE_NAMESPACE
  PG_USERNAME: $PG_USERNAME
  PG_DB_NAME: $PG_DB_NAME
